version: '3'

services:

    comet:
        image: telefonicaiot/fiware-sth-comet:${COMET_VERSION}
        ports:
            - "8666:8666"
        deploy:
            replicas: 1
        environment:
            - STH_HOST=0.0.0.0
            - DB_URI=${MONGO_SERVICE_URI}
            - REPLICA_SET=${REPLICASET_NAME}
            - LOGOPS_LEVEL=DEBUG
        networks:
            - frontend
            - backend

networks:
    default:
        driver_opts:
            com.docker.network.driver.mtu: ${DOCKER_MTU:-1500}
    frontend:
        driver: overlay
        external: true
    backend:
        driver: overlay
        external: true
